// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back_app_sr.Infra.Context;

#nullable disable

namespace back_app_sr.Infra.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240207232516_AdicionarCategoria")]
    partial class AdicionarCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back_app_sr.Domain.Models.Additional", b =>
                {
                    b.Property<int>("AdditionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdditionalId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AdditionalId");

                    b.ToTable("Additionals");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.CategoryItemModel", b =>
                {
                    b.Property<int>("CategoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryItemId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CategoryItemId");

                    b.ToTable("CategoryItem");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.DeliveryModel", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("DeliveryId");

                    b.HasIndex("TabId")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.ItemModel", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("CategoryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.OrderModel", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdditionalId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId");

                    b.HasIndex("TabId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.QuickSale", b =>
                {
                    b.Property<Guid>("QuickSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("QuickSaleId");

                    b.ToTable("QuickSales");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.QuickSaleItem", b =>
                {
                    b.Property<Guid>("QuickSaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuickSaleId")
                        .HasColumnType("uuid");

                    b.HasKey("QuickSaleItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("QuickSaleId");

                    b.ToTable("QuickSaleItems");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.TabModel", b =>
                {
                    b.Property<Guid>("TabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TabType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("TabId");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.TabPayment", b =>
                {
                    b.Property<Guid>("TabPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsChangeRequested")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TabId")
                        .HasColumnType("uuid");

                    b.HasKey("TabPaymentId");

                    b.HasIndex("TabId");

                    b.ToTable("TabPayments");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.DeliveryModel", b =>
                {
                    b.HasOne("back_app_sr.Domain.Models.TabModel", "TabModel")
                        .WithOne("DeliveryModel")
                        .HasForeignKey("back_app_sr.Domain.Models.DeliveryModel", "TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabModel");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.ItemModel", b =>
                {
                    b.HasOne("back_app_sr.Domain.Models.CategoryItemModel", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.OrderModel", b =>
                {
                    b.HasOne("back_app_sr.Domain.Models.TabModel", "TabModel")
                        .WithMany("Orders")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabModel");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.QuickSaleItem", b =>
                {
                    b.HasOne("back_app_sr.Domain.Models.ItemModel", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_app_sr.Domain.Models.QuickSale", "QuickSale")
                        .WithMany("QuickSaleItems")
                        .HasForeignKey("QuickSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("QuickSale");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.TabPayment", b =>
                {
                    b.HasOne("back_app_sr.Domain.Models.TabModel", "TabModel")
                        .WithMany("Payments")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabModel");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.CategoryItemModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.QuickSale", b =>
                {
                    b.Navigation("QuickSaleItems");
                });

            modelBuilder.Entity("back_app_sr.Domain.Models.TabModel", b =>
                {
                    b.Navigation("DeliveryModel")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
